"""sync subtotal

Revision ID: 029b84ad9f5b
Revises: ae6f478b8221
Create Date: 2026-03-19 01:33:57.129056

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '029b84ad9f5b'
down_revision = 'ae6f478b8221'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('earnings', sa.Column('real_photos_sold', sa.Float(), nullable=False))
    op.add_column('orders', sa.Column('subtotal', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'subtotal')
    op.drop_column('earnings', 'real_photos_sold')
    # ### end Alembic commands ###
