"""Add is_active to Photographer model

Revision ID: b783c052b57f
Revises: 3ad2ffc8a500
Create Date: 2026-02-24 13:24:47.721958

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b783c052b57f'
down_revision = '3ad2ffc8a500'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('earnings_photographer_id_fkey'), 'earnings', type_='foreignkey')
    op.create_foreign_key(None, 'earnings', 'photographers', ['photographer_id'], ['id'])
    op.drop_constraint(op.f('photo_sessions_photographer_id_fkey'), 'photo_sessions', type_='foreignkey')
    op.create_foreign_key(None, 'photo_sessions', 'photographers', ['photographer_id'], ['id'])
    
    # 1. Add column as nullable with a server default
    op.add_column('photographers', sa.Column('is_active', sa.Boolean(), nullable=True, server_default=sa.true()))
    
    # 2. Update existing rows to set is_active to True where it is NULL
    op.execute('UPDATE photographers SET is_active = TRUE WHERE is_active IS NULL')

    # 3. Alter column to be non-nullable, removing the server default
    op.alter_column('photographers', 'is_active',
               existing_type=sa.Boolean(),
               nullable=False,
               server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('photographers', 'is_active')
    op.drop_constraint(None, 'photo_sessions', type_='foreignkey')
    op.create_foreign_key(op.f('photo_sessions_photographer_id_fkey'), 'photo_sessions', 'photographers', ['photographer_id'], ['id'], ondelete='RESTRICT')
    op.drop_constraint(None, 'earnings', type_='foreignkey')
    op.create_foreign_key(op.f('earnings_photographer_id_fkey'), 'earnings', 'photographers', ['photographer_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###
